services:
  frontend:
    build: ./front-end
    container_name: script4store-frontend
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.script4store-frontend.rule=Host(`script4.store`)"
      - "traefik.http.routers.script4store-frontend.entrypoints=web"
      - "traefik.http.services.script4store-frontend.loadbalancer.server.port=60000"
    restart: unless-stopped
    networks:
      - traefik-net

  backend:
    build: ./back-end
    container_name: script4store-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.script4store-backend.rule=Host(`script4.store`) && PathPrefix(`/api`)"
      - "traefik.http.routers.script4store-backend.entrypoints=web"
      - "traefik.http.services.script4store-backend.loadbalancer.server.port=16000"
    restart: unless-stopped
    networks:
      - traefik-net

  router-api:
    build: ./tvm/roteador/back-end
    container_name: script4store-router-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-api.rule=Host(`script4.store`) && PathPrefix(`/tvm-roteador/api`)"
      - "traefik.http.routers.router-api.entrypoints=web"
      - "traefik.http.services.router-api.loadbalancer.server.port=7000"
    restart: unless-stopped
    networks:
      - traefik-net

  router-frontend:
    build: ./tvm/roteador/front-end
    container_name: script4store-router-frontend
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-frontend.rule=Host(`script4.store`) && PathPrefix(`/tvm-roteador`)"
      - "traefik.http.routers.router-frontend.entrypoints=web"
      - "traefik.http.services.router-frontend.loadbalancer.server.port=7001"
      - "traefik.http.middlewares.router-frontend-stripprefix.stripprefix.prefixes=/tvm-roteador"
      - "traefik.http.middlewares.router-frontend-stripprefix.stripprefix.forceSlash=true"
      - "traefik.http.routers.router-frontend.middlewares=router-frontend-stripprefix"
      - "traefik.http.services.router-frontend.loadbalancer.passHostHeader=true"
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
