services:
  frontend:
    build: ./front-end
    container_name: script4store-frontend
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.script4store-frontend.rule=Host(`script4.store`)"
      - "traefik.http.routers.script4store-frontend.entrypoints=web"
      - "traefik.http.services.script4store-frontend.loadbalancer.server.port=60000"
    restart: unless-stopped
    networks:
      - traefik-net

  backend:
    build: ./back-end
    container_name: script4store-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.script4store-backend.rule=Host(`script4.store`) && PathPrefix(`/api`)"
      - "traefik.http.routers.script4store-backend.entrypoints=web"
      - "traefik.http.services.script4store-backend.loadbalancer.server.port=16000"
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
