version: '3.8'

services:

  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  frontend:
    build: ./front-end
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`script4.store`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    restart: unless-stopped

  backend:
    build: ./back-end
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`script4.store`) && PathPrefix(`/bash`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.stripbash.stripprefix.prefixes=/bash"
      - "traefik.http.routers.backend.middlewares=stripbash"
    restart: unless-stopped
