version: '3.8'

services:
  api:
    build: .
    container_name: script4store-backend
    ports:
      - "16000:16000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=portfolio_db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`script4.store`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=16000"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: script4store-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  app-network:
    external: true

volumes:
  mongodb_data: 